#!/bin/bash
#PBS -l select=1:ncpus=24:mem=400gb
#PBS -l walltime=00:59:00
######PBS -q delightLONGQ
#PBS -q shortCPUQ
#PBS -N Stage

cd $PBS_O_WORKDIR
module purge

#source /home/m.calandrabuonaura/intel/oneapi/setvars.sh
source /shares/DELIGHT/Compilers/intel_2025_hpc3/intel_2025_hpc/oneapi/setvars.sh



PW=/shares/DELIGHT/Codes/q-e-qe-7.5NC_hpc3/q-e-qe-7.5CN/bin/pw.x
PH=/shares/DELIGHT/Codes/q-e-qe-7.5NC_hpc3/q-e-qe-7.5CN/bin/pw.x 
BANDS=/shares/DELIGHT/Codes/q-e-qe-7.5NC_hpc3/q-e-qe-7.5CN/bin/bands.x


# the following is not actually used:
#espresso_dir=../q-e-qe-6.7MaX-Release
####################################################################

#mpirun -n 48 ${PW} -npool 1 -in TriK.relax.in > TriK.relaxK222.out_step1
#mpirun -n 96 ${PW} -npool 4 -in  K2TaCl6.vc-relax.in_2  > K2TaCl6.vc-relax.out_2
mpirun -n 24 ${PW} -npool 4 -in  vc-relax.in  > vc-relax.out

